# Basic Information 
title: Yiguang Zhu
position: Ph.D. Candidate
affiliation: Johns Hopkins University
affiliation_link: https://www.jhu.edu/
affiliation_logo: ./assets/img/jhu1.png
email: yzhu99 (at) jh.edu

# Search Engine Optimization (SEO)
keywords: yiguang zhu, zhu yiguang, zhuyiguang, 朱益广
canonical: https://zhuyg.com
description: Ph.D. candidate in the Department of Environmental Health and Engineering at Johns Hopkins University. His research focuses on health policy and new approach methods like microphysiological systems.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
linkedin: https://www.linkedin.com/in/yiguangzhu/


# Images 
avatar: ./assets/img/avatar.jpg

# Footnotes
footnote: Powered by Jekyll and Minimal Light theme.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
